// ============================================================
//  STATE — Type Attack
// ============================================================

export const gameState = {
  score:             0,
  lives:             3,
  level:             1,
  highScore:         parseInt(localStorage.getItem("highScore") || "0", 10),
  isPlaying:         false,
  isPaused:          false,
  isMuted:           false,
  animationId:       null,
  currentInput:      "",
  activeWord:        null,
  isFrozen:          false,
  freezeTimer:       null,
  levelUpTimer:      null,
  modalPauseTimer:   null,
  modalPauseActive:  false,
  mistakes:          0,
  lastFailSoundAt:   0,
  bossMode:          false,
  bossModeEndsAt:    0,
  lastBossLevel:     0,
};

export const config = {
  canvas: {
    width:  800,
    height: 600,
  },
  word: {
    minSpeed:  0.5,
    maxSpeed:  3.5,
    spawnRate: 2000,
    fontSize:  24,
  },
  difficulty: {
    minSpawn:            650,
    spawnDecay:          140,
    speedRamp:           0.18,
    wrongKeyPenalty:     5,
    mistakeLifeThreshold:5,
    bossDurationMs:      14000,
    bossSpawn:           450,
    bossSpeedBoost:      0.6,
  },
};

export const wordBank = [
  // 3-letter
  "ace", "arc", "bit", "bug", "cat", "cod", "cop", "cpu", "cry", "cut",
  "dex", "dig", "dot", "duo", "era", "eye", "fog", "fun", "gem", "git",
  "gun", "hex", "hit", "hub", "ice", "ion", "key", "lag", "lap", "led",
  "lex", "log", "lux", "map", "mod", "net", "nix", "nod", "orb", "opt",
  "pad", "pan", "pod", "pop", "ray", "rgb", "run", "set", "sky", "sql",
  "tag", "tap", "tip", "top", "url", "usr", "via", "vim", "war", "web",
  "win", "zip", "zap",

  // 4-letter
  "apex", "arch", "atom", "axis", "bash", "beam", "beta", "bind", "blob",
  "boot", "byte", "call", "chip", "clan", "clip", "code", "coil", "core",
  "ctrl", "curl", "cyan", "dark", "dash", "data", "deck", "deep", "demo",
  "diff", "disk", "dive", "dome", "doom", "dual", "dump", "edge", "emit",
  "enum", "exec", "exit", "fast", "file", "fire", "flag", "flow", "flux",
  "font", "fork", "form", "frag", "free", "fuse", "game", "gate", "glow",
  "gold", "grid", "grow", "hack", "hash", "heap", "helm", "hero", "hook",
  "host", "html", "http", "hull", "hunt", "icon", "init", "java", "join",
  "jump", "kern", "kill", "king", "lamp", "lang", "lean", "lens", "link",
  "lint", "list", "live", "load", "lock", "logo", "loot", "loop", "lore",
  "loss", "lost", "make", "mark", "mask", "math", "maze", "menu", "mesh",
  "meta", "mine", "mint", "mock", "mode", "moon", "move", "name", "nano",
  "node", "norm", "null", "open", "orbs", "over", "pack", "page", "pain",
  "pair", "pass", "path", "pipe", "plan", "play", "plot", "plug", "plus",
  "poll", "port", "post", "prev", "proc", "prog", "push", "puts", "quit",
  "race", "raid", "rank", "read", "real", "rect", "redo", "refs", "repo",
  "rest", "risk", "road", "rock", "role", "root", "rule", "rust", "safe",
  "salt", "save", "scan", "seed", "self", "send", "ship", "shot", "show",
  "sign", "size", "skip", "slot", "slow", "snap", "snow", "sock", "sort",
  "span", "spec", "spin", "spot", "star", "stop", "swap", "sync", "task",
  "team", "test", "text", "tick", "tile", "time", "todo", "tool", "tree",
  "trim", "true", "tube", "tune", "type", "unit", "undo", "user", "util",
  "view", "void", "wait", "warn", "wave", "wide", "wiki", "wind", "wire",
  "word", "work", "wrap", "yaml", "yarn", "zero", "zone",

  // 5-letter
  "agent", "alert", "alien", "alpha", "array", "async", "atlas", "await",
  "batch", "begin", "bench", "block", "boost", "bound", "brace", "break",
  "build", "burst", "cache", "catch", "chain", "chaos", "chart", "check",
  "chunk", "cigar", "class", "clean", "clear", "click", "clone", "close",
  "cloud", "codec", "color", "comet", "const", "count", "craft", "crash",
  "crawl", "crazy", "crypt", "cycle", "debug", "decay", "delay", "delta",
  "depth", "drain", "drift", "drive", "drone", "earth", "embed", "empty",
  "error", "event", "every", "exact", "extra", "fable", "false", "fancy",
  "fatal", "fetch", "field", "final", "fixed", "flame", "flash", "float",
  "focus", "forge", "found", "frame", "frost", "fully", "gamma", "ghost",
  "given", "glyph", "grant", "graph", "group", "guard", "guess", "guide",
  "guild", "handy", "happy", "heads", "heavy", "helix", "https", "index",
  "infer", "inner", "input", "intel", "inter", "issue", "iteration",
  "karma", "laser", "later", "layer", "learn", "level", "light", "limit",
  "linux", "local", "logic", "login", "lower", "lunar", "magic", "major",
  "match", "merge", "minor", "model", "motor", "mount", "mouse", "multi",
  "mutex", "mysql", "nebula","nginx", "night", "noise", "nonce", "north",
  "occur", "offer", "often", "onion", "onset", "optic", "orbit", "order",
  "other", "outer", "oxide", "ozone", "panel", "parse", "patch", "pause",
  "phase", "pixel", "place", "plain", "plane", "plant", "plate", "point",
  "power", "prime", "print", "probe", "proxy", "pulse", "purge", "push",
  "queue", "query", "quick", "quota", "radar", "radio", "raise", "range",
  "rapid", "ratio", "reach", "realm", "redis", "regex", "relay", "remix",
  "reply", "reset", "retry", "reuse", "rider", "right", "rigid", "robot",
  "rouge", "round", "route", "rules", "rupee", "scala", "scale", "scene",
  "scope", "score", "scout", "scram", "scrub", "seize", "serve", "setup",
  "seven", "shade", "shape", "share", "sharp", "shell", "shift", "shine",
  "sigma", "sigil", "sixth", "skill", "slash", "slice", "slide", "small",
  "smart", "smoke", "solid", "solve", "sound", "south", "space", "spawn",
  "speed", "spend", "split", "spray", "squad", "stack", "stage", "stake",
  "start", "state", "steal", "steam", "steel", "storm", "story", "style",
  "super", "surge", "swift", "table", "token", "topic", "total", "touch",
  "track", "trade", "trail", "train", "trait", "trend", "trial", "trick",
  "trust", "truth", "tuple", "turbo", "twist", "ultra", "union", "unity",
  "until", "upper", "upset", "usage", "valid", "value", "vault", "verge",
  "verse", "video", "vigor", "viral", "visit", "vista", "vital", "vivid",
  "voice", "watch", "water", "where", "which", "while", "white", "whole",
  "width", "world", "write", "wrong", "xenon", "yield",

  // 6-letter
  "action", "active", "actual", "advent", "afford", "agency", "agenda",
  "agile", "alpine", "anchor", "answer", "anyone", "append", "arcade",
  "arrive", "assign", "attack", "aurora", "author", "avenue", "backup",
  "banner", "battle", "beacon", "binary", "binary", "branch", "bridge",
  "buffer", "bundle", "button", "bypass", "camera", "cancel", "canvas",
  "castle", "center", "cipher", "circle", "client", "clippy", "cobalt",
  "combat", "commit", "config", "cookie", "cosmos", "create", "credit",
  "cursor", "damage", "decode", "defend", "delete", "deploy", "design",
  "detect", "device", "dialog", "docker", "domain", "effect", "encode",
  "engine", "entity", "escape", "export", "extend", "filter", "finger",
  "finish", "follow", "footer", "freeze", "galaxy", "global", "handle",
  "header", "health", "hidden", "hybrid", "impact", "import", "inline",
  "insert", "intent", "invoke", "island", "kernel", "launch", "layout",
  "legacy", "linear", "listen", "lookup", "lumine", "manage", "manual",
  "marker", "matrix", "memory", "method", "mirror", "mobile", "module",
  "motion", "nebula", "nested", "neural", "normal", "notice", "object",
  "offset", "online", "option", "output", "packet", "parent", "parser",
  "photon", "planet", "plugin", "portal", "prefix", "prompt", "proton",
  "pulsar", "python", "quasar", "random", "reason", "record", "reduce",
  "refact", "remote", "rename", "render", "repeat", "report", "rescue",
  "return", "review", "revert", "reward", "rotate", "router", "sample",
  "script", "search", "secret", "secure", "select", "sensor", "serial",
  "server", "signal", "simple", "single", "sketch", "slider", "source",
  "splash", "spring", "sprint", "stable", "static", "status", "stream",
  "strict", "string", "struct", "submit", "switch", "symbol", "syntax",
  "system", "target", "tensor", "thread", "toggle", "tracer", "tunnel",
  "typeof", "update", "vector", "vertex", "visual", "widget", "window",
  "zenith",

  // 7+ letter (hard / boss words)
  "ancient", "android", "animate", "boolean", "browser", "captain",
  "cascade", "channel", "cluster", "compile", "compute", "connect",
  "console", "context", "control", "convert", "counter", "creative",
  "cryptic", "culture", "dataset", "decrypt", "defense", "destiny",
  "develop", "digital", "discord", "display", "dynamic", "element",
  "emperor", "encrypt", "exclude", "execute", "firefox", "flatten",
  "fractal", "freqent", "frontal", "gateway", "general", "genesis",
  "gravity", "handler", "horizon", "hyper",   "imagine", "include",
  "indices", "initial", "integer", "iterate", "journey", "kingdom",
  "latency", "library", "machine", "maximum", "message", "minimum",
  "mission", "network", "neutral", "numeric", "observe", "orbital",
  "payload", "percent", "persist", "phantom", "pioneer", "polygon",
  "process", "program", "quantum", "reactor", "receive", "request",
  "resolve", "respond", "restart", "runtime", "scanner", "segment",
  "service", "session", "setting", "silicon", "skyscraper", "soldier",
  "stellar", "storage", "success", "surface", "suspend", "terminal",
  "timeout", "tracker", "trigger", "twisted", "unicode", "universe",
  "unknown", "upgrade", "varchar", "venture", "version", "warrior",
  "webhook", "website", "wrapper",

  // 8+ letter (extreme)
  "absolute", "abstract", "asterisk", "asteroid", "backbone",
  "callback", "cardinal", "champion", "cluster",  "compiler",
  "complete", "compress", "constant", "consumer", "contract",
  "database", "deadlock", "debugger", "decision", "deferred",
  "diagonal", "director", "disaster", "document", "download",
  "endpoint", "engineer", "ethereum", "evaluate", "executor",
  "explorer", "external", "feedback", "firewall", "flagship",
  "frontend", "function", "generate", "hardware", "infinite",
  "instance", "integral", "iterator", "keyboard", "language",
  "launcher", "linkable", "listener", "manifest", "maximize",
  "minimize", "modifier", "momentum", "mongoose", "multiple",
  "navigate", "nebulous", "observer", "operator", "optimize",
  "overflow", "override", "parallel", "pipeline", "platform",
  "position", "postgres", "practice", "priority", "producer",
  "property", "protocol", "provider", "quantify", "question",
  "reassign", "receiver", "redirect", "register", "regulate",
  "relation", "relative", "renderer", "rerender", "resource",
  "response", "retrieve", "scaffold", "schedule", "selector",
  "sentinel", "sequence", "skeleton", "snapshot", "software",
  "solution", "spectrum", "standard", "strategy", "strength",
  "subclass", "supernova", "template", "thousand", "throttle",
  "transfer", "transmit", "universe", "validate", "variable",
  "viewport", "wireless",
];